version: '2'
services:
  minecraft_server:
    container_name: minecraft_server
    image: ubuntu
    volumes:
      - /root/minecraft:/home/ubuntu
    network_mode: bridge
    ports:
      - 25565:25565
    command: >
      bash -c "apt update &&
      apt dist-upgrade -y &&
      apt install openjdk-11-jre-headless wget -y &&
      cd /home/ubuntu &&
      chmod 744 /home/ubuntu/installed_jar.sh &&
      ./installed_jar.sh &&
      chmod 744 /home/ubuntu/server.jar &&
      echo "eula=true" > eula.txt &&
      rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man &&
      java -jar -Xmx512M server.jar nogui"

